# Generated by Django 3.2.10 on 2021-12-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
    ]
